### PR TITLE
remove jquery-hashchange dep & replace it with native browser api

### PR DESCRIPTION
**Pull request by jekrb**
I was experiencing bugs with the hashchange jquery plugin not firing events when the hash changed, causing the search to not work.

This pull request fixes that issue by replacing the whole plugin with `window.addEventListener('hashchange',` which is a native browser api and I also updated the docs

### CODE REVIEW

**Comment by davishmcclurg** [comment]
Hi @jekrb, thanks for the contributions.

We originally used jquery-hashchange to support browsers that don't support the native `hashchange` event and I don't think we want to get rid of it unless there's a good reason.

Can you describe the bugs you experienced? It would be great to get something reproducible that someone here can debug.

**Comment by jekrb** [comment]
Hey yeah :)

For me the hashchange plugin would only detect a hashchange once. Changing the hash any of number of times afterwards wouldn't be detected.  Switching to the native browser api works well for me though.

hmmm

maybe instead changing _this_ plugin, would it be alright if I made a new swiftype module specifically for modern browser?

the hashchange event is pretty well supported https://caniuse.com/#search=hashchange
but i totes understand if you'd rather keep jquery-hashchange 🌴

**Comment by davishmcclurg** [comment]
How were you triggering the hash change? In my testing, it seems to handle manually updating the has in the address bar and pressing back/forward.

**Comment by jekrb** [comment]
I was trying to change the hash by changing text in the input field and hitting <enter> (trying to mimic what it would be like for a user to change their input query)

**Comment by davishmcclurg** [comment]
Hmm, that sounds like a bug. Is there any way I can get access to a reproducible case?

**Comment by thekaveman** [comment]
👍 for this change - the native browser API is now widely supported and it's been 7 years since the dependent library was touched (*ages* on the internet, and *eons* in the javascript world!)

**Comment by jekrb** [comment]
hey sorry, unfortunately I don't have a reproducible case in the wild as I'm using this change on production.

I see @davishmcclurg point with supporting older browsers and keeping the library stable. I also do think theres some benefit in replacing the dependency with a native api, including less surface area to test.  I'd love to have time to perhaps make a version of the library that doesn't require jquery & jquery-hashchange and also publish to npm. However, I don't really have the time, so maybe some one else will see this and feel inspired :)

**Comment by thekaveman** [comment]
@jekrb regarding this proposed PR: 

The removal of `$(window).hashchange();` actually changes the behavior in certain cases - for example, I found that when I am on a page and have executed a search, reloading the page (e.g. `Ctrl+R`) fails to re-execute the search, without this line.

In standard jQuery, the same could be accomplished using `$(window).trigger("hashchange");`

**Comment by jekrb** [comment]
Oooh yeah good point. I had to check for the stp hash on page load, then perform a search if necessary.

**Comment by JasonStoltz** [comment]
Closing this in favor of #35

**Pull request closed without merging**
